messageTypes = { "PUBLIC_IP_NOTIF4": 0,
                 "PUBLIC_IP_NOTIF6": 1,
                 "PUBLIC_IP_NOTIFICATION_REQUEST": 2,
                 "CURRENT_SERVER_TIME": 5,
                 "SIGNATURE": 6,
                 "IPV4_SHA256_TASK": 10,
                 "IPV6_SHA256_TASK": 11,
                 "TASK_REPLY_NEW_CERT": 20,
                 "TASK_REPLY_KNOWN_CERT": 21,
                 "FP_VERIFY_REQUEST": 50,
                 "FP_VERIFY_RESULT": 60,
                 "CERT_VERIFY_REQUEST": 100,
                 "CERT_VERIFY_RESULT": 110 }

messageNames = {  0 : "PUBLIC_IP_NOTIF4",
                  1 : "PUBLIC_IP_NOTIF6",
                  2 : "PUBLIC_IP_NOTIFICATION_REQUEST",
                  5 : "CURRENT_SERVER_TIME",
                  6 : "SIGNATURE",
                  10 : "IPV4_SHA256_TASK",
                  11 : "IPV6_SHA256_TASK",
                  20 : "TASK_REPLY_NEW_CERT",
                  21 : "TASK_REPLY_KNOWN_CERT",
                  50 : "FP_VERIFY_REQUEST",
                  60 : "FP_VERIFY_RESULT",
                  100 : "CERT_VERIFY_REQUEST",
                  110 : "CERT_VERIFY_RESULT" }
